; See https://github.com/samuelgr/Xidi/wiki/Configuration for full details

; Xidi SDL3 Plugin
Plugin = SDL
ControllerBackend = SDL3

; Default setting values even without mentioning the configurations
[Log]
Enabled                             = no
Level                               = 1

[Properties]
MouseSpeedScalingFactorPercent      = 100
UseBuiltInProperties                = yes
CircleToSquarePercentStickLeft      = 0
CircleToSquarePercentStickRight     = 0
ForceFeedbackEffectStrengthPercent  = 100
DeadzonePercentStickLeft            = 0
DeadzonePercentStickRight           = 0
DeadzonePercentTriggerLT            = 0
DeadzonePercentTriggerRT            = 0
SaturationPercentStickLeft          = 100
SaturationPercentStickRight         = 100
SaturationPercentTriggerLT          = 100
SaturationPercentTriggerRT          = 100

[Mapper]
Type                = GameName

[CustomMapper:GameName]
Template            = StandardGamepad

; Default DirectInput keybinds
StickLeftX          = Axis(X)
StickLeftY          = Axis(Y)
StickRightX         = Axis(Z)
StickRightY         = Axis(RotZ)

DpadUp              = Pov(Up)
DpadDown            = Pov(Down)
DpadLeft            = Pov(Left)
DpadRight           = Pov(Right)

ButtonA             = Button(1)
ButtonB             = Button(2)
ButtonX             = Button(3)
ButtonY             = Button(4)

ButtonLB            = Button(5)
ButtonRB            = Button(6) 
TriggerLT           = Button(7)
TriggerRT           = Button(8)
ButtonBack          = Button(9)
ButtonStart         = Button(10)
ButtonLS            = Button(11)
ButtonRS            = Button(12)

; Remove ; below to uncomment and use the [Workarounds]
;[Workarounds]
;ActiveVirtualControllerMask = 0x01
;PollReturnCode = 0
;IgnoreEnumObjectsCallbackReturnCode = no
;UseShortVirtualControllerNames = no
